# Generated by Django 5.2 on 2025-04-13 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='公司描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目标题')),
                ('job_title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('job_description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='职位要求')),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='薪资范围')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作地点')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='headhunting.company', verbose_name='关联公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('education', models.CharField(choices=[('high_school', '高中'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('phd', '博士'), ('other', '其他')], max_length=20, verbose_name='最高学历')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业院校')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('experience_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('current_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前公司')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前职位')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='技能')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='工作经历')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resumes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已投递'), ('reviewing', '审核中'), ('interview', '面试中'), ('offer', '已录用'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='submitted', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_submissions', to='headhunting.project', verbose_name='项目')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='headhunting.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '简历投递记录',
                'verbose_name_plural': '简历投递记录',
                'ordering': ['-submitted_at'],
                'unique_together': {('resume', 'project')},
            },
        ),
    ]
