# Generated by Django 5.2 on 2025-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunting', '0002_projectstatus_resumestatus_paymentrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/', verbose_name='简历文件'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_1_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司1'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_1_description',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述1'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_1_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='时间段1'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_1_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位1'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_2_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司2'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_2_description',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述2'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_2_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='时间段2'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_2_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位2'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_3_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司3'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_3_description',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述3'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_3_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='时间段3'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp_3_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位3'),
        ),
    ]
