# Generated by Django 5.2 on 2025-04-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunting', '0003_resume_resume_file_resume_work_exp_1_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='headhunting.resume', verbose_name='简历')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '简历收藏',
                'verbose_name_plural': '简历收藏',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'user')},
            },
        ),
    ]
